
Mrapport: 	Mrapport.pdf
	@evince	Mrapport.pdf&
Mrapport.pdf:	Mrapport.tex  LatexAmeliore.tex LatexColor.tex LatexMathematique.tex LatexMiseEnPage.tex LatexProgramme.tex LatexSimple.tex LatexSlides.tex LatexSource.tex LatexTables.tex Mrapport.tex Mslides.tex texte.tex
	@pdflatex Mrapport.tex
